/**
 * Levelo Export Manager
 * Generates ZIP bundles (complete multi-file project, ready-to-build Capacitor mobile app,
 * and standalone offline HTML game file).
 */

import JSZip from 'jszip';
import type { GameProject, ProjectAsset } from './types';
import { bundleProjectHtml } from './bundler';
import { downloadDataUrl } from './asset-utils';

/**
 * Converts a Base64 / Data URL string into Uint8Array for binary ZIP storage.
 */
function dataUrlToUint8Array(dataUrl: string): Uint8Array {
  const parts = dataUrl.split(',');
  const base64 = parts[1] || '';
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

/**
 * Trigger browser file download from a Blob.
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * 1. Export standard project ZIP with all files and assets.
 */
export async function exportProjectZip(project: GameProject, assets: ProjectAsset[] = []): Promise<Blob> {
  const zip = new JSZip();

  // Add text files (index.html, scripts, styles, subfolders)
  for (const [filePath, content] of Object.entries(project.files)) {
    zip.file(filePath, content);
  }

  // Add binary assets inside /assets folder
  if (assets.length > 0) {
    const assetsFolder = zip.folder('assets');
    if (assetsFolder) {
      for (const asset of assets) {
        if (asset.data && asset.data.startsWith('data:')) {
          const rawBytes = dataUrlToUint8Array(asset.data);
          assetsFolder.file(asset.name, rawBytes);
        }
      }
    }
  }

  // Add Levelo README
  const readmeContent = `# ${project.title}

Created with Levelo (https://levelo.ai)

## Running Locally
1. Serve the directory with any local static web server:
   \`\`\`bash
   npx serve .
   # or
   python3 -m http.server 8080
   \`\`\`
2. Open \`http://localhost:8080\` in any modern web browser.

## Assets
Project assets are placed in the \`assets/\` directory and loaded relative to \`index.html\`.
`;
  zip.file('README.md', readmeContent);

  return zip.generateAsync({ type: 'blob' });
}

/**
 * 2. Export single standalone offline HTML file.
 */
export function exportStandaloneHtml(project: GameProject, assets: ProjectAsset[] = []): string {
  const bundled = bundleProjectHtml(project.files, assets);
  return `<!-- Generated by Levelo (https://levelo.ai) -->\n${bundled}`;
}

/**
 * 3. Export ready-to-build Mobile App (Capacitor) ZIP project.
 */
export async function exportCapacitorZip(project: GameProject, assets: ProjectAsset[] = []): Promise<Blob> {
  const zip = new JSZip();
  const sanitizedSlug = project.title
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .substring(0, 20) || 'game';

  const appId = `com.levelo.${sanitizedSlug}`;
  const appName = project.title.replace(/["\\]/g, '');

  // 1. package.json
  const packageJson = {
    name: `${sanitizedSlug}-mobile`,
    version: '1.0.0',
    description: `${appName} mobile game created with Levelo`,
    private: true,
    scripts: {
      'build': 'echo "Web assets are in www folder"',
      'cap:sync': 'cap sync',
      'cap:open:android': 'cap open android',
      'cap:open:ios': 'cap open ios'
    },
    dependencies: {
      '@capacitor/core': '^6.0.0',
      '@capacitor/android': '^6.0.0',
      '@capacitor/ios': '^6.0.0',
      '@capacitor/screen-orientation': '^6.0.0',
      '@capacitor/status-bar': '^6.0.0'
    },
    devDependencies: {
      '@capacitor/cli': '^6.0.0'
    }
  };
  zip.file('package.json', JSON.stringify(packageJson, null, 2));

  // 2. capacitor.config.ts
  const capacitorConfig = `import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: '${appId}',
  appName: '${appName}',
  webDir: 'www',
  server: {
    androidScheme: 'https'
  },
  plugins: {
    StatusBar: {
      overlaysWebView: true
    }
  }
};

export default config;
`;
  zip.file('capacitor.config.ts', capacitorConfig);

  // 3. www/ folder with the bundled standalone web game
  const wwwFolder = zip.folder('www');
  if (wwwFolder) {
    const standaloneHtml = bundleProjectHtml(project.files, assets);
    wwwFolder.file('index.html', standaloneHtml);

    // Also copy separate assets if needed
    if (assets.length > 0) {
      const wwwAssets = wwwFolder.folder('assets');
      if (wwwAssets) {
        for (const a of assets) {
          if (a.data && a.data.startsWith('data:')) {
            wwwAssets.file(a.name, dataUrlToUint8Array(a.data));
          }
        }
      }
    }
  }

  // 4. README.md with clear instructions on how to build Android APK and iOS apps
  const readmeContent = `# ${appName} - Mobile App Project (Capacitor)

This folder contains a complete, configured Capacitor mobile wrapper for **${appName}**, ready to build for Android and iOS using Android Studio or Xcode.

---

### Prerequisites
- [Node.js](https://nodejs.org) (v18 or newer)
- [Android Studio](https://developer.android.com/studio) (for Android APK / Google Play)
- [Xcode](https://developer.apple.com/xcode/) (macOS only, for iOS IPA / App Store)

---

### Step 1: Install Dependencies
Open a terminal in this extracted directory and run:
\`\`\`bash
npm install
\`\`\`

---

### Step 2: Add Android Platform & Build APK
1. Initialize the native Android folder:
   \`\`\`bash
   npx cap add android
   \`\`\`

2. Sync web assets:
   \`\`\`bash
   npx cap sync
   \`\`\`

3. Open in Android Studio:
   \`\`\`bash
   npx cap open android
   \`\`\`

4. In Android Studio:
   - Click **Build** > **Build Bundle(s) / APK(s)** > **Build APK(s)**.
   - Or click the green **Play** ▶ button to run directly on your connected phone or emulator!

---

### Step 3: Add iOS Platform (macOS only)
1. \`\`\`bash
   npx cap add ios
   npx cap sync
   npx cap open ios
   \`\`\`
2. In Xcode, select your team under **Signing & Capabilities** and run on your iPhone or simulator.

---
*Created with Levelo (https://levelo.ai)*
`;
  zip.file('README.md', readmeContent);

  return zip.generateAsync({ type: 'blob' });
}
